# Generated by Django 2.1.5 on 2019-08-30 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Copy_1', models.IntegerField(blank=True, default=0)),
                ('Cheat_2', models.IntegerField(blank=True, default=0)),
                ('Coop_3', models.IntegerField(blank=True, default=0)),
                ('Detective_4', models.IntegerField(blank=True, default=0)),
                ('CopyKit_5', models.IntegerField(blank=True, default=0)),
                ('Simp_6', models.IntegerField(blank=True, default=0)),
                ('Random_7', models.IntegerField(blank=True, default=0)),
                ('Grudger_7', models.IntegerField(blank=True, default=0)),
                ('Points_both_co_op', models.IntegerField(blank=True, default=2)),
                ('Points_both_cheat', models.IntegerField(blank=True, default=0)),
                ('Points_one_cheat', models.IntegerField(blank=True, default=3)),
                ('Points_one_coop', models.IntegerField(blank=True, default=-1)),
                ('No_of_games', models.IntegerField(blank=True, default=10)),
                ('Error', models.IntegerField(blank=True, default=0)),
                ('Pref_1_ans', models.IntegerField(blank=True, default=0)),
                ('Pref_2_ans', models.IntegerField(blank=True, default=0)),
                ('Pref_3_ans', models.IntegerField(blank=True, default=0)),
                ('Pref_4_ans', models.IntegerField(blank=True, default=0)),
                ('flag', models.IntegerField(blank=True, default=0)),
                ('num_eliminate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(blank=True, default=0)),
                ('result', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('num', models.IntegerField(blank=True, default=1)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
