# Generated by Django 2.2.3 on 2019-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(max_length=50)),
                ('Name_2', models.CharField(max_length=50)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
    ]
