# Generated by Django 2.2.3 on 2019-08-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20190817_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
