# Generated by Django 2.2.3 on 2019-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20190817_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Input',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
