# Generated by Django 2.2.3 on 2019-08-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_userprofile_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char_1', models.IntegerField(blank=True, default=0)),
                ('Char_2', models.IntegerField(blank=True, default=0)),
                ('Char_3', models.IntegerField(blank=True, default=0)),
                ('Char_4', models.IntegerField(blank=True, default=0)),
                ('Char_5', models.IntegerField(blank=True, default=0)),
                ('Char_6', models.IntegerField(blank=True, default=0)),
                ('Char_7', models.IntegerField(blank=True, default=0)),
                ('Char_8', models.IntegerField(blank=True, default=0)),
                ('Char_9', models.IntegerField(blank=True, default=0)),
                ('Char_10', models.IntegerField(blank=True, default=0)),
                ('Char_11', models.IntegerField(blank=True, default=0)),
                ('Char_12', models.IntegerField(blank=True, default=0)),
                ('Char_13', models.IntegerField(blank=True, default=0)),
                ('Char_14', models.IntegerField(blank=True, default=0)),
                ('Char_15', models.IntegerField(blank=True, default=0)),
                ('Char_16', models.IntegerField(blank=True, default=0)),
                ('Char_17', models.IntegerField(blank=True, default=0)),
                ('Char_18', models.IntegerField(blank=True, default=0)),
                ('Char_19', models.IntegerField(blank=True, default=0)),
                ('Char_20', models.IntegerField(blank=True, default=0)),
                ('Char_21', models.IntegerField(blank=True, default=0)),
                ('Char_22', models.IntegerField(blank=True, default=0)),
                ('Char_23', models.IntegerField(blank=True, default=0)),
                ('Char_24', models.IntegerField(blank=True, default=0)),
                ('Char_25', models.IntegerField(blank=True, default=0)),
                ('Points_both_co_op', models.IntegerField(blank=True, default=0)),
                ('Points_both_cheat', models.IntegerField(blank=True, default=0)),
                ('Points_one_cheat', models.IntegerField(blank=True, default=0)),
                ('Points_one_coop', models.IntegerField(blank=True, default=0)),
                ('No_of_games', models.IntegerField(blank=True, default=0)),
                ('Error', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
