# Generated by Django 2.2.3 on 2019-08-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='No_of_games',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='Points_both_co_op',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='Points_one_cheat',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='case',
            name='Points_one_coop',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
