# Generated by Django 2.2.3 on 2019-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20190824_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Pref_1_ans',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='Pref_2_ans',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='Pref_3_ans',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='Pref_4_ans',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
