# Generated by Django 2.2.3 on 2019-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20190824_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
