# Generated by Django 2.2.3 on 2019-08-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20190829_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Name_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Name_2',
        ),
    ]
