# Generated by Django 2.1.5 on 2019-08-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20190829_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='num_eliminate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
