# Generated by Django 2.1.7 on 2019-08-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20190830_1131'),
        ('person', '0013_userprofile_result'),
    ]

    operations = [
    ]
