# Generated by Django 2.2.3 on 2019-08-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_userprofile_result'),
        ('person', '0012_auto_20190830_1131'),
    ]

    operations = [
    ]
