# Generated by Django 2.2.3 on 2019-08-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_merge_20190830_1532'),
        ('person', '0014_merge_20190830_1010'),
    ]

    operations = [
    ]
