# Generated by Django 2.1.7 on 2019-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_merge_20190830_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='flag',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
