# Generated by Django 2.2.3 on 2019-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_merge_20190830_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='flag',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
